version: "3.7"
services:
  # PostgreSQL container setup
  postgres:
    image: postgres:10.0-alpine
    container_name: pgs_db
    environment:
      - POSTGRES_USER=calendar_user
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_DB=calendar_db
    volumes:
      - ../db/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    networks:
      db-net:
        aliases:
          - postgres

  # RabbitMQ container setup
  rabbitmq:
    image: rabbitmq:3.8.0-alpine
    container_name: rmq
    ports:
      - "56721:5672"
    networks:
      rabbit-net:
        aliases:
          - rabbitmq

  # Notification service
  notification:
    container_name: notification
    build:
      context: ../.
      dockerfile: ./deployments/notification/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbit-net
    restart: on-failure

  # Watcher service
  watcher:
    container_name: watcher
    build:
      context: ../.
      dockerfile: ./deployments/watcher/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - db-net
      - rabbit-net
    restart: on-failure

  # Go Calendar service
  go-calendar:
    container_name: gcs
    build:
      context: ../.
      dockerfile: ./deployments/go-calendar/Dockerfile
    volumes:
      - ../configs:/opt/go-calendar/configs
    depends_on:
      - postgres
    ports:
      - "7070:7070"
    networks:
      db-net:
        aliases:
          - go-calendar
    restart: on-failure

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.13.1
    volumes:
      - ../configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - go-calendar
      - notification
      - postgresql-exporter
    networks:
      - db-net
      - rabbit-net
    restart: on-failure

  postgresql-exporter:
    container_name: psql-exporter
    image: wrouesnel/postgres_exporter:v0.8.0
    ports:
      - 9187:9187
    volumes:
      - ../configs/prometheus/queries.yml:/etc/prometheus/queries.yml
    networks:
      - db-net
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:5432/calendar_db?sslmode=disable&user=calendar_user&password=calendar
      - PG_EXPORTER_DISABLE_DEFAULT_METRICS=true
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/prometheus/queries.yml

# Network definitions
networks:
  db-net:
    driver: bridge
  rabbit-net:
    driver: bridge
