host = "127.0.0.1"
port = "7070"
loglevel = 2.0

[db]
name = "calendar_db"
user = "calendar_user"
sslmode = "disable"
host = "127.0.0.1"
port = "54321"
password = "some_pwd"

[queue]
  host = "localhost"
  port = "5672"
  user = "guest"
  password = "guest"
  interval = "24h"
